### PR TITLE
fix mod conflicts with chat mixins

### LINKED ISSUE #42: [Bug/Suggestion/Improvement] : MixinChatScreen mod incompatibilities.
So, I am the Journeymap developer, we have an incompatibility due to how you handle your chat mixin on init() to open your chat window. 
```
    @Inject(method = "init", at = @At("HEAD"), cancellable = true)
    public void chatInit(CallbackInfo ci) {
        // Open the AdvancedChatScreen instead
        GuiBase.openGui(new AdvancedChatScreen(this.originalChatText));
        ci.cancel();
    }
```

So, on our fullscreen map we allow users to chat while the screen is open. However, with this mixin creating and setting a new screen, it closes all other screens when chat.init is called. I can probably work around it, but I'd rather not since this mixin may also interfere with other mods. 

I would suggest instead of the init methods,  you do a modify args on the 
`this.minecraft.setScreen(new ChatScreen(this.input.getValue())` so it adds your chat screens
In the following classes/methods these are mojangmap, probably similar in yarn.

mojmap:InBedChatScreen -> yarn:SleepingChatScreen
```
    public void onPlayerWokeUp() {
        if (this.input.getValue().isEmpty()) {
            this.minecraft.setScreen(null);
        } else {
            this.minecraft.setScreen(new ChatScreen(this.input.getValue()));
        }
    }
```

mojmap:Minecraft -> yarn:MinecraftClient
```
    private void openChatScreen(String string) {
        ChatStatus chatStatus = this.getChatStatus();
        if (!chatStatus.isChatAllowed(this.isLocalServer())) {
            this.gui.setOverlayMessage(chatStatus.getMessage(), false);
        } else {
            this.setScreen(new ChatScreen(string));
        }
    }
```

This should correct incompatibilities.

### PR DESCRIPTION
**Pull request by mysticdrew**
fixes #42

### CODE REVIEW

File: src/main/java/io/github/darkkronicle/advancedchatcore/mixin/MixinSleepingChatScreen.java [hunk 1]
```diff
@@ -7,24 +7,29 @@
...
 import org.spongepowered.asm.mixin.injection.At;
-import org.spongepowered.asm.mixin.injection.Inject;
-import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
+import org.spongepowered.asm.mixin.injection.ModifyArg;
 
 @Environment(EnvType.CLIENT)
 @Mixin(SleepingChatScreen.class)
-public class MixinSleepingChatScreen {
+public class MixinSleepingChatScreen extends ChatScreen {
+    public MixinSleepingChatScreen() {
```
Comment (mysticdrew) [inline src/main/java/io/github/darkkronicle/advancedchatcore/mixin/MixinSleepingChatScreen.java:24]: I tried to avoid doing this, but it is needed to get access to `chatField`.

**Comment by mysticdrew** [comment]
I could not get your git hooks to run on my machine. 
Running the spotlessApply task
would give this error
```
Step 'removeUnusedImports' found problem in 'src\main\java\io\github\darkkronicle\advancedchatcore\mixin\MixinChatScreen.java':
null
java.lang.reflect.InvocationTargetException
```

**Comment by DarkKronicle** [comment]
Thanks for the PR! Yeah I need to remove spotless

**Comment by DarkKronicle** [comment]
Today or tomorrow I’ll test this out. I think your solution works really well for avoiding conflicts

**Comment by DarkKronicle** [comment]
Everything looks like it works! Gonna add a couple new things but it should hopefully be published today.
